"""Added defence, remaining_health and attack

Revision ID: 40dbbe156be3
Revises: 73ccd3c60f87
Create Date: 2025-04-11 17:47:32.224794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40dbbe156be3'
down_revision: Union[str, None] = '73ccd3c60f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lokacija', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lokacija')

    # ### end Alembic commands ###
