"""Added lokacija column to the User table

Revision ID: 6f614426b761
Revises: 4c5c0228c32a
Create Date: 2025-04-12 20:11:53.177755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f614426b761'
down_revision: Union[str, None] = '4c5c0228c32a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_market', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_id_community_market', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lokacija', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lokacija')

    with op.batch_alter_table('community_market', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id_community_market', type_='foreignkey')

    # ### end Alembic commands ###
