"""Made a new combat table

Revision ID: 73ccd3c60f87
Revises: 67faf24e8031
Create Date: 2025-04-11 02:18:50.143632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ccd3c60f87'
down_revision: Union[str, None] = '67faf24e8031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'community_market', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'community_market', type_='foreignkey')
    # ### end Alembic commands ###
