"""Made a new user_id column in the community_market table

Revision ID: 76c9d70b4303
Revises: c75b86917e1e
Create Date: 2025-02-25 00:45:58.875710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c9d70b4303'
down_revision: Union[str, None] = 'c75b86917e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_market', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'community_market', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'community_market', type_='foreignkey')
    op.drop_column('community_market', 'user_id')
    # ### end Alembic commands ###
